# to build image:
# > docker-compose build

# to run container (and keep atached to the container)
# > docker-compose up [<service_name>]

# to run container as a daemon
# > docker-compose up -d [<service_name>]
# to attach to daemon container
# > docker exec -it <container_id> bash

# to stop the started container
# > docker-compose stop [<service_name>]

# to stop and remove the started container
# > docker-compose down [<service_name>]

version: "3"
services:
  android_ci:
    image: android_ci
    tty: true
    build:
      context: ..
      dockerfile: docker/AndroidCI.Ubuntu.Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTP_PROXY_HOST=${HTTP_PROXY_HOST}
        - HTTP_PROXY_PORT=${HTTP_PROXY_PORT}
    environment:
      - REPO_URL=${REPO_URL}
      - TARGET_PATH_WORKSPACE=/root/workspace
    volumes:
      - ${TARGET_PATH}:/root/workspace/
      - ${PRIVATE_KEY_REMOTE_PATH}:/root/provision/id_rsa
      - ../src/startup.sh:/root/startup.sh
    extra_hosts:
      - "nexus.nespresso.com:192.168.216.107"
  jenkins:
    image: jenkins
    user: root
    tty: true
    build:
      context: ..
      dockerfile: docker/Jenkins.Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTP_PROXY_HOST=${HTTP_PROXY_HOST}
        - HTTP_PROXY_PORT=${HTTP_PROXY_PORT}
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - $JENKINS_PORT:8080
    

