# to build image:
# > docker-compose build

# to run container (and keep atached to the container)
# > docker-compose up [<service_name>]

# to run container as a daemon
# > docker-compose up -d [<service_name>]
# to attach to daemon container
# > docker exec -it <container_id> bash

# to stop the started container
# > docker-compose stop [<service_name>]

# to stop and remove the started container
# > docker-compose down [<service_name>]

version: "3"
services:
  android_ci:
    image: android_ci
    tty: true
    build:
      context: ..
      dockerfile: docker/AndroidCI.Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTP_PROXY_HOST=${HTTP_PROXY_HOST}
        - HTTP_PROXY_PORT=${HTTP_PROXY_PORT}
    volumes:
      - ${TARGET_PATH}:/home/gradle/project/
    extra_hosts:
      - "nexus.nespresso.com:192.168.216.107"
  jenkins_ci:
    image: jenkins_ci
    user: root
    tty: true
    build:
      context: ..
      dockerfile: docker/Jenkins.Dockerfile
    volumes:
      - $JENKINS_HOME:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - $JENKINS_PORT:8080
    

