FROM sonatype/nexus3:3.18.1
LABEL MAINTAINER sergi.torrellas@soprasteria.com

ARG HTTP_PROXY
ARG HTTP_PROXY_HOST
ARG HTTP_PROXY_PORT
ARG APPCENTER_TOKEN

ENV HTTP_PROXY ${HTTP_PROXY}
ENV HTTPS_PROXY ${HTTP_PROXY}
ENV http_proxy ${HTTP_PROXY}
ENV https_proxy ${HTTP_PROXY}
ENV HTTP_PROXY_HOST ${HTTP_PROXY_HOST}
ENV HTTP_PROXY_PORT ${HTTP_PROXY_PORT}
